import 'package:flutter/material.dart';
import '../data/app_database.dart';
import '../models/clinical_record.dart';
import 'patients_screen.dart';
import 'security_backup_screen.dart';

class HomeScreen extends StatefulWidget{const HomeScreen({super.key,required this.database});final AppDatabase database;@override State<HomeScreen> createState()=>_HomeScreenState();}
class _HomeScreenState extends State<HomeScreen>{int _patients=0;@override void initState(){super.initState();_refresh();}Future<void> _refresh()async{final count=await widget.database.patientCount();if(mounted)setState(()=>_patients=count);}void _openPatients([RecordType? initialType])async{await Navigator.of(context).push(MaterialPageRoute(builder:(_)=>PatientsScreen(database:widget.database,initialRecordType:initialType)));_refresh();}
 @override Widget build(BuildContext context){final modules=[('Goniometria','Amplitude de movimento',Icons.straighten,RecordType.goniometry),('Força muscular','Escalas e evolução',Icons.fitness_center,RecordType.strength),('Avaliações','Avaliação fisioterapêutica',Icons.assignment_outlined,RecordType.assessment),('Evoluções','Registre cada atendimento',Icons.trending_up,RecordType.evolution),('Testes funcionais','Resultados por protocolo',Icons.timer_outlined,RecordType.functionalTest)];return Scaffold(appBar:AppBar(title:const Text('+Fisio',style:TextStyle(fontWeight:FontWeight.w800)),actions:[IconButton(tooltip:'Segurança e backup',onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const SecurityBackupScreen())),icon:const Icon(Icons.shield_outlined)),IconButton(onPressed:(){},icon:const Icon(Icons.workspace_premium_outlined))]),body:RefreshIndicator(onRefresh:_refresh,child:ListView(padding:const EdgeInsets.all(20),children:[Text('Seu consultório no seu celular',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('Dados locais, acompanhamento simples e evolução organizada.'),const SizedBox(height:20),Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.people_alt_outlined)),title:const Text('Pacientes',style:TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('$_patients cadastrados neste aparelho'),trailing:const Icon(Icons.chevron_right),onTap:()=>_openPatients())),const SizedBox(height:16),Text('Ferramentas',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),...modules.map((m)=>Card(child:ListTile(leading:Icon(m.$3),title:Text(m.$1,style:const TextStyle(fontWeight:FontWeight.w600)),subtitle:Text(m.$2),trailing:const Icon(Icons.chevron_right),onTap:()=>_openPatients(m.$4)))),const SizedBox(height:12),Card(child:ListTile(leading:const Icon(Icons.shield_outlined),title:const Text('Segurança e backup',style:TextStyle(fontWeight:FontWeight.bold)),subtitle:const Text('Proteja o app e faça cópias do prontuário local'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const SecurityBackupScreen()))))])));}}
