import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../services/backup_service.dart';
import '../services/google_drive_backup_service.dart';
import '../services/pro_service.dart';
import '../services/security_service.dart';
import 'pro_screen.dart';

class SecurityBackupScreen extends StatefulWidget{const SecurityBackupScreen({super.key});@override State<SecurityBackupScreen> createState()=>_SecurityBackupScreenState();}
class _SecurityBackupScreenState extends State<SecurityBackupScreen>{bool lock=false,loading=true,busy=false;String? googleEmail;List<DriveBackupInfo> cloud=[];final pro=ProService.instance;@override void initState(){super.initState();pro.addListener(_changed);pro.initialize();_load();}@override void dispose(){pro.removeListener(_changed);super.dispose();}void _changed(){if(mounted)setState((){});}
 Future<bool> _requirePro()async{if(pro.isPro)return true;await Navigator.push(context,MaterialPageRoute(builder:(_)=>const ProScreen()));return pro.isPro;}
 Future<void> _load()async{lock=await SecurityService.isLockEnabled();if(pro.isPro){final user=await GoogleDriveBackupService.currentUser();googleEmail=user?.email;if(user!=null){try{cloud=await GoogleDriveBackupService.listBackups();}catch(_){}}}if(mounted)setState(()=>loading=false);}
 Future<void> _toggle(bool value)async{if(value){if(!await SecurityService.canAuthenticate()){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Configure biometria ou bloqueio de tela no aparelho primeiro.')));return;}if(!await SecurityService.authenticate())return;}await SecurityService.setLockEnabled(value);if(mounted)setState(()=>lock=value);}
 Future<void> _connectGoogle()async{if(!await _requirePro())return;setState(()=>busy=true);try{final user=await GoogleDriveBackupService.connect();googleEmail=user?.email;if(user!=null)cloud=await GoogleDriveBackupService.listBackups();}catch(e){_msg('Falha ao conectar Google: $e');}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> _driveBackup()async{if(!await _requirePro())return;setState(()=>busy=true);try{await GoogleDriveBackupService.upload();cloud=await GoogleDriveBackupService.listBackups();_msg('Backup criptografado salvo no Google Drive.');}catch(e){_msg('Falha no backup do Drive: $e');}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> _driveRestore(DriveBackupInfo b)async{if(!await _requirePro())return;final yes=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Restaurar backup do Google Drive?'),content:Text('O prontuário local será substituído pelo backup ${b.modifiedTime==null?'selecionado':DateFormat('dd/MM/yyyy HH:mm').format(b.modifiedTime!.toLocal())}.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Restaurar'))]));if(yes!=true)return;setState(()=>busy=true);try{await GoogleDriveBackupService.restore(b);_msg('Backup restaurado. Reinicie o +Fisio para carregar os dados.');}catch(e){_msg('Falha ao restaurar: $e');}finally{if(mounted)setState(()=>busy=false);}}
 void _msg(String text){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(text)));}
 Future<void> _backup()async{setState(()=>busy=true);try{await BackupService.shareBackup();}catch(e){_msg('Falha no backup: $e');}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> _restore()async{final confirm=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Restaurar backup local?'),content:const Text('O prontuário atual será substituído pelos dados do arquivo selecionado.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Continuar'))]));if(confirm!=true)return;setState(()=>busy=true);try{final ok=await BackupService.restoreBackup();if(ok)_msg('Backup restaurado. Reinicie o +Fisio.');}catch(e){_msg('Falha na restauração: $e');}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Segurança e backup')),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[SwitchListTile(value:lock,onChanged:_toggle,secondary:const Icon(Icons.fingerprint),title:const Text('Bloqueio do +Fisio'),subtitle:const Text('Exigir biometria, PIN ou credencial do aparelho.')),const Divider(),Row(children:[Expanded(child:Text('Google Drive',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold))),if(!pro.isPro)const Chip(avatar:Icon(Icons.lock_outline,size:16),label:Text('PRO'))]),const SizedBox(height:8),Card(child:Padding(padding:const EdgeInsets.all(16),child:pro.isPro?Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.cloud_outlined),const SizedBox(width:12),Expanded(child:Text(googleEmail==null?'Nenhuma conta Google conectada':'Conectado: $googleEmail'))]),const SizedBox(height:12),if(googleEmail==null)FilledButton.icon(onPressed:busy?null:_connectGoogle,icon:const Icon(Icons.login),label:const Text('Conectar conta Google'))else ...[FilledButton.icon(onPressed:busy?null:_driveBackup,icon:const Icon(Icons.cloud_upload_outlined),label:const Text('Fazer backup agora')),const SizedBox(height:8),Text('${cloud.length} backup(s) disponíveis',style:Theme.of(context).textTheme.labelLarge),...cloud.take(5).map((b)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.cloud_done_outlined),title:Text(b.modifiedTime==null?'Backup +Fisio':DateFormat('dd/MM/yyyy HH:mm').format(b.modifiedTime!.toLocal())),subtitle:Text(b.name),trailing:IconButton(tooltip:'Restaurar',onPressed:busy?null:()=>_driveRestore(b),icon:const Icon(Icons.restore))))]]):Column(children:[const Icon(Icons.workspace_premium_outlined,size:38),const SizedBox(height:8),const Text('Backup no Google Drive é um recurso do +Fisio PRO.',textAlign:TextAlign.center),const SizedBox(height:12),FilledButton(onPressed:()=>_requirePro(),child:const Text('Conhecer +Fisio PRO'))]))),const SizedBox(height:18),Text('Backup manual',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),ListTile(enabled:!busy,leading:const Icon(Icons.backup_outlined),title:const Text('Exportar backup local'),subtitle:const Text('Salve uma cópia manual fora do aplicativo.'),onTap:_backup),ListTile(enabled:!busy,leading:const Icon(Icons.restore),title:const Text('Restaurar arquivo local'),subtitle:const Text('Importa um arquivo .mfbackup.'),onTap:_restore),if(busy)const Padding(padding:EdgeInsets.all(16),child:LinearProgressIndicator()),const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('Backups em nuvem são criptografados antes do upload. O backup manual continua disponível para todos os usuários.')))]));}
