import 'package:flutter/material.dart';
import '../services/backup_service.dart';
import '../services/security_service.dart';

class SecurityBackupScreen extends StatefulWidget{const SecurityBackupScreen({super.key});@override State<SecurityBackupScreen> createState()=>_SecurityBackupScreenState();}
class _SecurityBackupScreenState extends State<SecurityBackupScreen>{bool lock=false,loading=true,busy=false;@override void initState(){super.initState();_load();}Future<void> _load()async{lock=await SecurityService.isLockEnabled();if(mounted)setState(()=>loading=false);}
 Future<void> _toggle(bool value)async{if(value){if(!await SecurityService.canAuthenticate()){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Configure biometria ou bloqueio de tela no aparelho primeiro.')));return;}if(!await SecurityService.authenticate())return;}await SecurityService.setLockEnabled(value);if(mounted)setState(()=>lock=value);}
 Future<void> _backup()async{setState(()=>busy=true);try{await BackupService.shareBackup();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Falha no backup: $e')));}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> _restore()async{final confirm=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Restaurar backup?'),content:const Text('O prontuário atual será substituído pelos dados do arquivo selecionado. Antes da troca, o app cria uma cópia de segurança interna.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Continuar'))]));if(confirm!=true)return;setState(()=>busy=true);try{final ok=await BackupService.restoreBackup();if(ok&&mounted){await showDialog(context:context,builder:(c)=>AlertDialog(title:const Text('Backup restaurado'),content:const Text('Feche e abra novamente o +Fisio para carregar o prontuário restaurado.'),actions:[FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('OK'))]));}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Falha na restauração: $e')));}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Segurança e backup')),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[const Card(child:Padding(padding:EdgeInsets.all(16),child:Row(children:[Icon(Icons.health_and_safety_outlined),SizedBox(width:12),Expanded(child:Text('Os prontuários ficam neste aparelho. Proteja o acesso e mantenha um backup seguro para evitar perda de dados.'))]))),const SizedBox(height:12),SwitchListTile(value:lock,onChanged:_toggle,secondary:const Icon(Icons.fingerprint),title:const Text('Bloqueio do +Fisio'),subtitle:const Text('Exigir biometria, PIN ou credencial segura do aparelho ao abrir o app.')),const Divider(),ListTile(enabled:!busy,leading:const Icon(Icons.backup_outlined),title:const Text('Criar backup'),subtitle:const Text('Gera uma cópia local do banco para você guardar em um local seguro.'),trailing:const Icon(Icons.chevron_right),onTap:_backup),ListTile(enabled:!busy,leading:const Icon(Icons.restore),title:const Text('Restaurar backup'),subtitle:const Text('Importa um arquivo .mfbackup e substitui os dados locais.'),trailing:const Icon(Icons.chevron_right),onTap:_restore),if(busy)const Padding(padding:EdgeInsets.all(16),child:LinearProgressIndicator()),const SizedBox(height:18),const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('Atenção: backups, PDFs e CSVs podem conter dados sensíveis de saúde. O profissional é responsável por armazenar e compartilhar esses arquivos de forma segura.')))]));}
