import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../services/backup_service.dart';
import '../services/google_drive_backup_service.dart';
import '../services/security_service.dart';

class SecurityBackupScreen extends StatefulWidget{const SecurityBackupScreen({super.key});@override State<SecurityBackupScreen> createState()=>_SecurityBackupScreenState();}
class _SecurityBackupScreenState extends State<SecurityBackupScreen>{bool lock=false,loading=true,busy=false;String? googleEmail;List<DriveBackupInfo> cloud=[];@override void initState(){super.initState();_load();}
 Future<void> _load()async{lock=await SecurityService.isLockEnabled();final user=await GoogleDriveBackupService.currentUser();googleEmail=user?.email;if(user!=null){try{cloud=await GoogleDriveBackupService.listBackups();}catch(_){}}if(mounted)setState(()=>loading=false);}
 Future<void> _toggle(bool value)async{if(value){if(!await SecurityService.canAuthenticate()){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Configure biometria ou bloqueio de tela no aparelho primeiro.')));return;}if(!await SecurityService.authenticate())return;}await SecurityService.setLockEnabled(value);if(mounted)setState(()=>lock=value);}
 Future<void> _connectGoogle()async{setState(()=>busy=true);try{final user=await GoogleDriveBackupService.connect();googleEmail=user?.email;if(user!=null)cloud=await GoogleDriveBackupService.listBackups();}catch(e){_msg('Falha ao conectar Google: $e');}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> _driveBackup()async{setState(()=>busy=true);try{await GoogleDriveBackupService.upload();cloud=await GoogleDriveBackupService.listBackups();_msg('Backup criptografado salvo no Google Drive.');}catch(e){_msg('Falha no backup do Drive: $e');}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> _driveRestore(DriveBackupInfo b)async{final yes=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Restaurar backup do Google Drive?'),content:Text('O prontuário local será substituído pelo backup ${b.modifiedTime==null?'selecionado':DateFormat('dd/MM/yyyy HH:mm').format(b.modifiedTime!.toLocal())}.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Restaurar'))]));if(yes!=true)return;setState(()=>busy=true);try{await GoogleDriveBackupService.restore(b);_msg('Backup restaurado. Reinicie o +Fisio para carregar os dados.');}catch(e){_msg('Falha ao restaurar: $e');}finally{if(mounted)setState(()=>busy=false);}}
 void _msg(String text){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(text)));}
 Future<void> _backup()async{setState(()=>busy=true);try{await BackupService.shareBackup();}catch(e){_msg('Falha no backup: $e');}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> _restore()async{final confirm=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Restaurar backup local?'),content:const Text('O prontuário atual será substituído pelos dados do arquivo selecionado.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Continuar'))]));if(confirm!=true)return;setState(()=>busy=true);try{final ok=await BackupService.restoreBackup();if(ok)_msg('Backup restaurado. Reinicie o +Fisio.');}catch(e){_msg('Falha na restauração: $e');}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Segurança e backup')),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[SwitchListTile(value:lock,onChanged:_toggle,secondary:const Icon(Icons.fingerprint),title:const Text('Bloqueio do +Fisio'),subtitle:const Text('Exigir biometria, PIN ou credencial do aparelho.')),const Divider(),Text('Google Drive',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.cloud_outlined),const SizedBox(width:12),Expanded(child:Text(googleEmail==null?'Nenhuma conta Google conectada':'Conectado: $googleEmail'))]),const SizedBox(height:12),if(googleEmail==null)FilledButton.icon(onPressed:busy?null:_connectGoogle,icon:const Icon(Icons.login),label:const Text('Conectar conta Google'))else ...[FilledButton.icon(onPressed:busy?null:_driveBackup,icon:const Icon(Icons.cloud_upload_outlined),label:const Text('Fazer backup agora')),const SizedBox(height:8),Text('${cloud.length} backup(s) disponíveis',style:Theme.of(context).textTheme.labelLarge),...cloud.take(5).map((b)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.cloud_done_outlined),title:Text(b.modifiedTime==null?'Backup +Fisio':DateFormat('dd/MM/yyyy HH:mm').format(b.modifiedTime!.toLocal())),subtitle:Text(b.name),trailing:IconButton(tooltip:'Restaurar',onPressed:busy?null:()=>_driveRestore(b),icon:const Icon(Icons.restore)) ))]]))),const SizedBox(height:18),Text('Backup manual',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),ListTile(enabled:!busy,leading:const Icon(Icons.backup_outlined),title:const Text('Exportar backup local'),subtitle:const Text('Salve uma cópia manual fora do aplicativo.'),onTap:_backup),ListTile(enabled:!busy,leading:const Icon(Icons.restore),title:const Text('Restaurar arquivo local'),subtitle:const Text('Importa um arquivo .mfbackup.'),onTap:_restore),if(busy)const Padding(padding:EdgeInsets.all(16),child:LinearProgressIndicator()),const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('Os backups enviados ao Google Drive são criptografados antes do upload. O +Fisio solicita acesso somente à área privada de dados do próprio aplicativo no Drive.')))]));}
